import Layout from "@/components/layouts/Layout";
import { ReduxProvider } from "./redux-provider";

export const metadata = {
	title: "Convolution Simulation",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ReduxProvider>
			<Layout>{children}</Layout>
		</ReduxProvider>
	);
}
