import Layout from "@/components/layouts/Layout";

export const metadata = {
	title: "Convolution Simulator",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <Layout>{children}</Layout>;
}
