import Navigation from "@/components/Navigation";

export const metadata = {
	title: "Convolution Simulation",
	description: "Generated by create next app",
};

export default function UserLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div>
			<Navigation />
			{children}
		</div>
	);
}
